    <hr>
    <div class="footer_div">
    <table width="100%">
      <tr>
        <td class="footer" align="left">Centipede Pi Electron Spin version <?php echo $version; ?></td>
        <td class="footer" align="center"><a href='https://centipede.serve101.org/'>Centipede Systems Homepage</a></td>
        <td class="footer" align="right">&copy;2018, <a href='http://<?php echo $host; ?>/license.php'>license</a></td>
      </tr>
    </table>
    </div>
  </body>
</html>
